// <auto-generated />
// Generated deterministically by Software Logistics Build Server from .resx source.
using System.Globalization;
using System.Reflection;

namespace LagoVista.IoT.Logging.Resources
{
    public class LoggingResources
    {
        private static global::System.Resources.ResourceManager _resourceManager;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(_resourceManager, null))
                    _resourceManager = new global::System.Resources.ResourceManager("LagoVista.IoT.Logging.Resources.LoggingResources", typeof(LoggingResources).GetTypeInfo().Assembly);
                return _resourceManager;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private static string GetResourceString(string key, params string[] tokens)
        {
            var str = ResourceManager.GetString(key, CultureInfo.CurrentCulture);
            for (var i = 0; i < tokens.Length; i += 2)
                str = str.Replace(tokens[i], tokens[i + 1]);
            return str;
        }

//Resources:LoggingResources:LogRecord_Description
        public static string LogRecord_Description { get { return GetResourceString("LogRecord_Description"); } }
//Resources:LoggingResources:LogRecords_Title
        public static string LogRecords_Title { get { return GetResourceString("LogRecords_Title"); } }

        public static class Names
        {
            public const string LogRecord_Description = "LogRecord_Description";
            public const string LogRecords_Title = "LogRecords_Title";
        }
    }
}

